const INITIAL_CLINICS = [];

const INITIAL_USERS = [
  { username: 'admin', password: 'password', role: 'admin', clinicId: null, name: 'Super Administrator' }
];

const INITIAL_PATIENTS = [];
const INITIAL_VITALS = [];
const INITIAL_TEMPLATES = [];
const INITIAL_DRUGS = [];
const INITIAL_TESTS = [];
const INITIAL_ADVICE = [];
const INITIAL_APPOINTMENTS = [];
const INITIAL_BILLS = [];
const INITIAL_INSURANCE = [];
const INITIAL_ATTENDANCE = [];
const INITIAL_DOCTOR_SLOTS = [];
const INITIAL_DRUG_CATEGORIES = [];
const INITIAL_SPECIALITIES = [];

module.exports = {
  INITIAL_CLINICS,
  INITIAL_USERS,
  INITIAL_PATIENTS,
  INITIAL_VITALS,
  INITIAL_TEMPLATES,
  INITIAL_DRUGS,
  INITIAL_TESTS,
  INITIAL_ADVICE,
  INITIAL_APPOINTMENTS,
  INITIAL_BILLS,
  INITIAL_INSURANCE,
  INITIAL_ATTENDANCE,
  INITIAL_DOCTOR_SLOTS,
  INITIAL_DRUG_CATEGORIES,
  INITIAL_SPECIALITIES
};
